%% FEM base fun

x = linspace(0, 1, 21)';
y_real = [x(x<0.5).^2; 0.25; (x(x>0.5)-1).^2];
y_dot = (x-0.5).^2;

figure; plot(x, y_real, '-', x, y_dot, '.-', x, y_real*0, 'k', ...
    0.5*ones(1,2), [-1,1], 'k')
set(gca, 'YLim', [-0.25,0.5], ...
    'XTick', [0,0.5,1], ...
    'XTicklabel', {'x_{j-1}','x_j', 'x_{j+1}'},...
    'YTick', [],...
    'FontSize', 15)
grid on

%% DG base fun

x = linspace(0, 1, 21)';
y_real = [x(x<0.5).^2; 0.25; (x(x>0.5)-1).^2];
y_dot = (x-0.5).^2;

figure; plot(x, y_real, '-', x, y_dot, '.-', x, y_real*0, 'k', ...
    0.5*ones(1,2), [-1,1], 'k')
set(gca, 'YLim', [-0.25,0.5], ...
    'XTick', [0,0.5,1], ...
    'XTicklabel', {'x_{j-1}','x_j', 'x_{j+1}'},...
    'YTick', [],...
    'FontSize', 15)
grid on


%%